[package]
name = "ble-weatherstation-central"
version = "0.1.0"
authors = ["foldu <foldu@protonmail.com>"]
edition = "2018"
license = "Unlicense OR MIT"


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
askama = { version = "0.10.3", features = ["with-warp"] }
askama_warp = "0.10.0"
bitflags = "1.2.1"
byteorder = "1.3.4"
clap = "3.0.0-beta.2"
derive_more = "0.99.11"
directories-next = "2.0.0"
eyre = "0.6.2"
flume = "0.9.1"
futures-util = "0.3.7"
heed = "0.10.1"
rand = "0.7.3"
serde = { version = "1.0.117", features = ["derive"] }
serde_json = "1.0.59"
tokio = { version = "0.2.22", features = ["rt-threaded", "sync", "time", "signal", "macros"] }
tracing = "0.1.21"
tracing-subscriber = { version = "0.2.15", default-features = false, features = ["smallvec", "chrono", "fmt", "ansi"] }
warp = { version =  "0.2.5", default-features = false }
zbus = { git = "https://gitlab.freedesktop.org/zeenix/zbus", rev = "d9bfcab6327a1f2e71abdd1e9a560189efcc84bd" }
zerocopy = "0.3.0"
zvariant = { git = "https://gitlab.freedesktop.org/zeenix/zbus", rev = "d9bfcab6327a1f2e71abdd1e9a560189efcc84bd" }
